language: scala
scala:
  - 2.11.8

sudo: required
# https://github.com/travis-ci/travis-ci/issues/6928#issuecomment-264227708
group: deprecated
dist: trusty
jdk:
  - oraclejdk8

services:
  - docker

before_install:
  # https://github.com/travis-ci/travis-ci/issues/6928#issuecomment-264227708
  - jdk_switcher use oraclejdk8
  - ./docker/provision.sh

